apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-2048
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-2048
  template:
    metadata:
      labels:
        app: app-2048
    spec:
      containers:
      - name: app-2048
        image: tsmith4014/2048-app
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app-2048
spec:
  type: NodePort
  ports:
  - port: 80
  selector:
    app: app-2048